// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:notify/models/notification_action/notification_action.dart';
import 'package:notify/models/notification_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NotificationActionAdapter());
    registerAdapter(NotificationModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NotificationActionAdapter());
    registerAdapter(NotificationModelAdapter());
  }
}
